// <auto-generated />
using System;
using CarPoolSystem.Services.OfferRideAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPoolSystem.Services.OfferRideAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230927062237_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarPoolSystem.Services.OfferRideAPI.Model.Offer", b =>
                {
                    b.Property<int>("Offer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Offer_Id"));

                    b.Property<string>("Car_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone_no")
                        .HasColumnType("bigint");

                    b.Property<int>("Seat_Available")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Offer_Id");

                    b.ToTable("Offer");

                    b.HasData(
                        new
                        {
                            Offer_Id = 1,
                            Car_Name = "Honda",
                            DepartureTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Hyderabad",
                            Name = "Roma",
                            Phone_no = 9569045767L,
                            Seat_Available = 5,
                            Source = "Hyderabad"
                        },
                        new
                        {
                            Offer_Id = 2,
                            Car_Name = "Alto",
                            DepartureTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Hyderabad",
                            Name = "Kaju",
                            Phone_no = 9569045767L,
                            Seat_Available = 5,
                            Source = "Hyderabad"
                        },
                        new
                        {
                            Offer_Id = 3,
                            Car_Name = "BMW",
                            DepartureTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Hyderabad",
                            Name = "Raju",
                            Phone_no = 9569045767L,
                            Seat_Available = 5,
                            Source = "Hyderabad"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
